apiVersion: v1
kind: Service
metadata:
  name: simple-server
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: simple-server