apiVersion: v1
kind: Service
metadata:
  name: app-server
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: app-server