apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
      - image: nginx
        name: web-server
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      - image: openweb/git-sync
        name: git-sync
        volumeMounts:
        - name: html
          mountPath: /git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/joshdcuneo/learn-k8s.git
        - name: GIT_SYNC_DEST
          value: /git
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_REV
          value: FETCH_HEAD
        - name: GIT_SYNC_WAIT
          value: "10"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: html
