apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
      - image: nginx
        name: web-server
        volumeMounts:
        - name: web-server-config
          readOnly: true
          mountPath: /etc/nginx/conf.d
        - name: html
          mountPath: /var/www/html
          readOnly: true
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      - image: openweb/git-sync
        name: git-sync
        volumeMounts:
        - name: html
          mountPath: /git
        envFrom:
          - configMapRef:
              name: git-sync-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: html
      - name: web-server-config
        configMap:
          name: web-server-config
          items:
            - key: default.conf
              path: default.conf

