apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 4444
      targetPort: http
      name: http
  selector:
    app: static-server